DROP TABLE kontrole CASCADE CONSTRAINTS;
DROP TABLE pracownicy CASCADE CONSTRAINTS;
DROP TABLE samochody CASCADE CONSTRAINTS;
DROP TABLE placowki CASCADE CONSTRAINTS;
DROP TABLE zmiany_pracownicze CASCADE CONSTRAINTS;
DROP TABLE stanowiska CASCADE CONSTRAINTS;
DROP TABLE dane_pojazdow CASCADE CONSTRAINTS;
DROP TABLE stany_pojazdow CASCADE CONSTRAINTS;
DROP TABLE produkcja_pojazdow CASCADE CONSTRAINTS;
DROP TABLE wlasciciele CASCADE CONSTRAINTS;
DROP TABLE informacje_osobowe CASCADE CONSTRAINTS;
DROP TABLE adresy CASCADE CONSTRAINTS; 
DROP SEQUENCE adresy_seq;
DROP SEQUENCE informacje_seq;
DROP SEQUENCE placowki_seq;
DROP SEQUENCE pracownicy_seq;
DROP SEQUENCE zmiany_pr_seq;
DROP SEQUENCE kontrole_seq;
DROP PROCEDURE zmiana_stawki;
DROP PROCEDURE zmiana_premii;
DROP PROCEDURE zmiana_premii_st;
DROP PROCEDURE zmiana_stawki_st;
DROP PROCEDURE zmiana_ceny;
drop view view_wlasciciele;
drop view view_placowki;
drop view view_pracownicy;
drop view view_samochody;
drop view view_kontrole;
drop view view_kontrole_week;
drop view view_utarg;